from pathlib import Path
from typing import Optional

from nicegui.element import Element


class Viewer360(Element, component='viewer360.js'):
    """A 360° spin viewer widget for NiceGUI.

    Supports two modes:
    - **Sprite mode**: a single sprite sheet WebP containing all frames packed
      in a grid. Recommended for production (one HTTP request). When the sprite
      was generated by ``p360-process``, all geometry parameters are embedded
      as XMP metadata and the widget reads them automatically — only ``sprite``
      is required.
    - **Sequence mode**: individual frame images (WebP, PNG, etc.).
      Useful for development or when frames are generated dynamically.

    Minimal usage (sprite mode, metadata embedded by p360-process):

        from nicegui_p360 import Viewer360
        Viewer360(sprite='/static/products/mug01/sprite.webp')

    Full usage with explicit parameters:

        Viewer360(
            sprite='/static/products/mug01/sprite.webp',
            frame_count=64,
            display_width=600,
            auto_spin=0.5,
        )

    Sequence mode:

        frames = [f'/static/products/mug01/frame_{i:03d}.webp' for i in range(1, 43)]
        Viewer360(frames=frames, frame_count=42, frame_width=800, frame_height=450)
    """

    def __init__(
        self,
        *,  # make all subsequent arguments keyword-only
        # Input source — provide one of these
        sprite: Optional[str] = None,
        frames: Optional[list[str]] = None,

        # Frame geometry — auto-read from XMP when using sprite mode + p360-process
        # Must be provided explicitly in sequence mode or if XMP is absent
        frame_count: Optional[int] = None,
        cols: Optional[int] = None,
        frame_width: Optional[int] = None,
        frame_height: Optional[int] = None,

        # Display
        display_width: int = 600,
        background: str = 'transparent',

        # Interaction
        drag_sensitivity: int = 8,
        auto_spin: float = 0.0,   # rpm; 0 disables auto-spin
    ) -> None:
        """Create a 360° spin viewer.

        :param sprite: URL of the sprite sheet image (sprite mode).
            When generated by ``p360-process``, geometry is read from embedded
            XMP metadata automatically.
        :param frames: list of frame image URLs (sequence mode)
        :param frame_count: total number of frames (auto-read from XMP in sprite mode)
        :param cols: columns in sprite grid (auto-read from XMP in sprite mode)
        :param frame_width: frame width in sprite px (auto-read from XMP in sprite mode)
        :param frame_height: frame height in sprite px (auto-read from XMP in sprite mode)
        :param display_width: rendered viewer width in pixels (height is auto-computed)
        :param background: CSS background color (default: 'transparent')
        :param drag_sensitivity: pixels of drag per frame step (lower = more sensitive)
        :param auto_spin: rotation speed in RPM; 0 disables auto-spin
        """
        if sprite is None and frames is None:
            raise ValueError("Provide either 'sprite' or 'frames'.")
        if sprite is not None and frames is not None:
            raise ValueError("Provide either 'sprite' or 'frames', not both.")
        if frames is not None:
            for required, name in [(frame_count, 'frame_count'),
                                   (frame_width,  'frame_width'),
                                   (frame_height, 'frame_height')]:
                if required is None:
                    raise ValueError(f"'{name}' is required in sequence mode.")

        super().__init__()
        self.add_resource(Path(__file__).parent)

        self._props['spriteSrc'] = sprite
        self._props['framesSrc'] = frames

        # the following props will be read from XMP in sprite mode if not provided explicitly:
        self._props['frameCount'] = frame_count
        self._props['cols'] = cols
        self._props['frameWidth'] = frame_width
        self._props['frameHeight'] = frame_height

        self._props['displayWidth'] = display_width
        self._props['background'] = background
        self._props['dragSensitivity'] = drag_sensitivity
        self._props['autoSpin'] = auto_spin
